### ISSUE TITLE
Caches returns nothing, resulting in Access denied etc.

### ISSUE THREAD

**Issue by surgicalcoder** [opserver/Opserver#101]
Occasionally, will get random "Access Denied" when on a page, doing a few refreshes will result in things working again - can lead to uncertainty, i.e. "Did I take that server out of the HAProxy pool?"

Managed to catch it in the act, screenshots attached:

![screenshot_313](https://cloud.githubusercontent.com/assets/1169543/10162437/1bd81e8e-66a3-11e5-863b-a3f3c2a8c231.png)
![screenshot_312](https://cloud.githubusercontent.com/assets/1169543/10162438/1bdb5482-66a3-11e5-8f2f-7f208e4fd75f.png)

**Comment by NickCraver** [comment]
Can you check your windows event log? That's looking like an app restart at first glance - you can check app uptime in just `/about` as well.

**Comment by surgicalcoder** [comment]
Turns out Opserver is hammering CPU (under powered machine), moved to larger machine, issue no longer seen!
