### ISSUE TITLE
Scheduled tasks view

### ISSUE THREAD

**Issue by georgeduckett** [opserver/Opserver#110]
Hi, is there any interest/plans for being able to get stats about windows schedule tasks, similar to the SQL jobs view?
Would this be something worth pursuing?

**Comment by NickCraver** [comment]
I'm not necessarily opposed to it, but where would such data come from? Also what would it be filtered to? There are many tasks out of the box in the various categories in the tree...that seems like a lot of potential noise that would need solving. 

I can't say we actually have a use for this at Stack, but I can totally see use cases - have examples?

**Comment by georgeduckett** [comment]
Re. where to get the data, I think WMI could be an option, which might make sense as that already exists as a provider. Alternatively using classes in `Microsoft.Win32.TaskScheduler` could be an option too. I've used https://www.nuget.org/packages/TaskScheduler in the past.

Re filtering, possibly excluding anything in the built-in Microsoft folder could work, or better perhaps would be a regex type setting (similar to how the categories sections of the dashboard settings work). I'd imagine some criteria would need to dictate which servers/machines to query (unless the dashboard configuration is used). I'd imagine somewhere there would be a setting for which machines to query.
I'm not familiar with the dashboard providers other than WMI so I'm not too sure how a provider/data source and views would best fit with what's already provided.

As for use cases here we have a few servers with specific tasks, usually running simple console apps at specific times, as well as some tasks that run on them all (virus scanning, defrag, auditing etc). It would be useful to have somewhere central to monitor them (rather than dealing with notifications for each task individually).

**Comment by NickCraver** [comment]
@georgeduckett  the WMI polling is one of many possible providers, so I'm not sure it's an awesome option for the dependency. I'm not against it, but I'm totally unaware of what percentage of users are using which providers (if any at all for the Dashboard). I know a great many people deploy Opserver for just SQL, Redis, HAProxy, etc. - but I assume you picture scheduled tasks falling under the dashboard feature?

**Comment by NickCraver** [comment]
Closing this out lacking any clear path here.
