### ISSUE TITLE
SQL Instances not showing table details

### ISSUE THREAD

**Issue by GregWhiteDBA** [opserver/Opserver#114]
I am using the overhaul code, when browsing database table details for sql instances I get an error 500 
Object reference not set to an instance of an object. on line 7 of file:
Databases.Modal.Tables.cshtml 

Line 5:      Layout = "Databases.Modal.cshtml";
Line 6:      var s = Model.Instance;
Line 7:      var tables = s.GetTableInfo(Model.Database);
Line 8:  }
Line 9:  @if (tables.Data == null || !tables.LastPollSuccessful)

as a dba i see a lot of value in this and am hoping to get some c# knowledge in order to contribute on this so pointers appreciated.

**Comment by NickCraver** [comment]
Yeah this doesn't actually work in Overhaul right now - one of the few things to put back after breaking it earlier. I re-did all of the modal code to allow deep linking, etc. but the 2-level (or multi-level in general) is something I need to re-visit. I want to get this in ASAP and improve the feature at the same time...I'll update this issue as soon as I have something to test ready.

**Comment by NickCraver** [comment]
I almost have this working, just one last on-load deep linking issue to resolve which I should be able to do tomorrow. I gave it some styling love as well - thoughts?
<img width="1373" alt="screen shot 2016-02-19 at 10 23 25 pm" src="https://cloud.githubusercontent.com/assets/454813/13194225/a00b9508-d757-11e5-832e-7aac7450a2e2.png">
The column info is now loaded initially as well, so clicks are instant. It's really not that much HTML to send down to the client, so I'm just pre-loading it all in the initial popup to work around a few issues.

**Comment by NickCraver** [comment]
@GregWhiteDBA in the overhaul branch for testing - I'll fix deep links in the AM here.

**Comment by NickCraver** [comment]
Much better tables behavior is now available as of https://github.com/opserver/Opserver/commit/1d1a58544c72bffaa0846090a8f48f296a4b618f, enjoy! Let me know if you find any problems and I'll open this back up for tracking.

**Comment by GregWhiteDBA** [comment]
thanks Nick, I appreciate this isn't solely an SQL focused system however as a dba I have a number of items on my wish list and want to contribute. I will knock something up and raise it separately to get your thoughts. I will test the instance changes today

**Comment by GregWhiteDBA** [comment]
still getting same error for instances guess that bit is a work in  progress, i will try to figure it out
