### ISSUE TITLE
SQL: Database: Missing Indexes View

### ISSUE THREAD

**Issue by NickCraver** [opserver/Opserver#122]
Needs creating.

**Comment by kshyju** [comment]
@NickCraver I have a [commit](https://github.com/kshyju/Opserver/commit/4281d1faf177d95a297dbc2e0bc01630a4eb41b1) which enables this feature. Please take a look. Thanks!

This is a part of a PR #130

**Comment by NickCraver** [comment]
v1 is in, closing this out.
