### ISSUE TITLE
Dashboard not showing network values or graph when using WMI provider.

### ISSUE THREAD

**Issue by snoopydo** [opserver/Opserver#126]
Almost always we don't get any network data on the dashboard.  I had a bit of a dig around and I found a work-around that works for me.

In Opserver.Core/Data/Dashboard/Node.cs, property PrimaryInterfaces appears to set its private member variable before the interface data is available from the underlying WMI provider.  If I amend the if null test to also test for _primaryInterfaces.Count==0 then I get data shown in the dashboard.

Related to the above.  I would have thought perhaps the regex test to determine whether or not to include the interface in the dashboard should be matched against or include the interface Caption or PrettyName properties?

**Comment by NickCraver** [comment]
WMI is a bit of an odd duck here, because it's refreshing the in-memory nodes rather than deserializing a new list as other providers do (which isn't necessarily bad, but creates some issues). I fixed the race with a tweak (so it doesn't keep re-running if there are no interfaces on the node) and I'll take a look at primary today.

The regex running against all isn't a bad idea, but I need to move it around. After the kids are out the door here I'll clean that up to fold into the IsLikelyPrimary property on the interface all in one spot.

Alternatively, it'd be better to get the teaming information pulled from WMI and Orion (Bosun has this) so we just *know* what the main interfaces are (to avoid double counting bytes), rather than guessing.

**Comment by NickCraver** [comment]
@snoopydo There's new code in the overhaul branch that expands the regex matching as well as cleans up a bit. Can you give latest a test please?

**Comment by snoopydo** [comment]
It appears to work.
Unfortunately I couldn't get 'overhaul' branch to build/run.  In the interests of quickly testing I copied the changes from commit e68dcb6cc5ca15d0a0024d5881f065b0a1e648de into 'master'.  I'll try getting the 'overhaul' branch running on my computer tomorrow morning.

**Comment by snoopydo** [comment]
At a bit of a dead end trying to get the 'overhaul' branch to build/run.
I'm using VS2013, with targeting packs for both .Net 4.6 & 4.6.1 installed.
Looking into the project file the Opserver project is targeting 4.6, however that's not showing in the list of target frameworks for that project, 4.5, 4.5.1, 4.5.2 & 4.6.1 are listed. The Opserver.Core project lists all of the frameworks, so not to sure the difference there.  If I select 4.6.1, I get a compiler error saying /langversion:6 (the web.config setting?) is invalid. I'm guessing I don't have a dependency installed?

**Comment by NickCraver** [comment]
I see you have the targeting packs, but do you actually have .Net 4.6 installed on the machine you're trying to run on? Opserver doesn't *strictly* need 4.6, but I'm setting the expectation early since I'll be targeting that .Net Platform generation on the move to .Net Core.

**Comment by snoopydo** [comment]
I believed so.  I did try reinstalling, starting with 4.5.2 and working my way up each version, they all reported that the version or a newer one was already installed.  
Went back to a simple console app to test. I can create a 4.5.2 x86 binary and have it run, selecting AnyCPU, x64 or 4.6 gives an error. either
<pre>Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x64".  </pre> or <pre>There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "System.Data", "AMD64". This mismatch may cause runtime failures.</pre>
Looking in the reference assembly folders the 4.6 there are no dlls, so I guess its not actually installed and the 4.5 installs are incomplete.

**Comment by snoopydo** [comment]
Installed VS2015 Community and things look much better. 
Back to original question. The WMI queries now throw an exception where they didn't before.  Looking at Opserver.Core/Data/Dashboard/Providers/WmiDataProvider.Polling.cs, UpdateNodeDataAsync() method mangles the Name property.
~~~C#
// overhaul 
Name = data.Domain != LocalDomainName ?
   $"{data.DNSHostName}.{data.Domain}" : data.DNSHostName;

// master
Name = data.DNSHostName;
~~~
ie I've listed servers SVR-1, SVR-2 & SVR-3 and these become SVR-1.Workgroup-name which won't resolve via DNS.  Almost all our servers are standalone and not part of a domain.

**Comment by NickCraver** [comment]
@snoopydo gotcha - I'll take a look tonight, it looks like PR #124 wasn't friendly to non-domains (which admittedly I didn't test either), we'll get it fixed.

**Comment by NickCraver** [comment]
@snoopydo Can you please give latest code a try? I just pushed some fixes for the domain assumptions.

**Comment by snoopydo** [comment]
@NickCraver I hate to be the bearer of bad news :(  Unfortunately it doesn't work.

I should have mentioned it earlier, my computer that I'm monitoring from and the server I'm likely to deploy it to are part of a company domain, but most of (but not all) the servers I'm wanting to monitor are not.

I'm probably missing the back story, but is there any reason to actually update the Name property at all, its specified in a config file and we've been able to make the initial connection to it why change it?

**Comment by NickCraver** [comment]
@snoopydo the WMI provider in general is mostly a PR and hasn't gotten proper love - your question is a good one. I'm back at work for Stack today but I'll take a look tonight...my guess is you're absolutely right, we just shouldn't update a working endpoint. I'll look at appropriately splitting the name to another property.

**Comment by NickCraver** [comment]
@snoopydo apologies, I've been slammed with other projects and didn't get to do a decent Opserver pass until now. I've just pushed a fix which leaves the endpoints alone and makes the dashboard naming updates cross-domain independent. Can you please give latest a try when you get a chance?

**Comment by snoopydo** [comment]
:+1: Its working.

However there is a display issue with the sparkline graphs on the /dashboard page.  They appear to be truncated and not scaled to the required size?  In the dashboard they're a 173x20 image, but the generated svg is 500x50.

**Comment by NickCraver** [comment]
@snoopydo the SVGs are scaled to fit a variety of dimensions, the nature of a sparkline makes the aspect ratio irrelevant (luckily). Can you post a screenshot of what's looking odd?

**Comment by snoopydo** [comment]
Looks to be an IE problem, Chrome displays the sparkline graphs as I expected to see them.

As highlighted, Chrome shows graphs
![capture-chrome](https://cloud.githubusercontent.com/assets/1243121/14838834/7beb13e0-0c79-11e6-96b0-b37ee73a76ed.PNG)

IE11, they're missing
![capture-ie11](https://cloud.githubusercontent.com/assets/1243121/14838839/87e084c8-0c79-11e6-986d-45317c76351f.PNG)

**Comment by NickCraver** [comment]
Older IE may not be supporting SVGs there - all modern versions should. Closing this out to clean up :)
