### ISSUE TITLE
SQL Server 2008 Reported Memory

### ISSUE THREAD

**Issue by martosource** [opserver/Opserver#127]
The calculation for memory on SQL Server older than 2012 is incorrect.

In SQLInstance,Memory.GetFetchSQL line 122 needs to change from:
`return FetchSQL.Replace("pages_kb", "single_pages_kb + multi_pages_kb");`
to 
`return FetchSQL.Replace("pages_kb", "(single_pages_kb + multi_pages_kb)");`

The brackets are missing for the UsedBytes column.

**Comment by NickCraver** [comment]
Thanks for the report, fixed in the `overhaul` branch!
