### ISSUE TITLE
SQL "Features: Error Fetching Features"

### ISSUE THREAD

**Issue by VictoriaD** [opserver/Opserver#129]
When I drill down into some of my SQL Instances, some of the sections on that page have missing data:
![missing](https://cloud.githubusercontent.com/assets/14888476/13352230/cc9ef232-dc83-11e5-8e3f-c4f666479370.png)
When I went along to the `/about` page, I found that had there had been errors retrieving the data:
![features](https://cloud.githubusercontent.com/assets/14888476/13352253/f348e38e-dc83-11e5-8bf1-eb4a6b0467b5.png)
However, on the `/admin/errors` page there is just the message 'No errors yet, yay!'

How can I find out what's wrong?

Is this related to why these instances are marked as red, and appear in the issues list? Because I can't tell why some of them are critical - they look fine! Although not everything with missing features is critical and vice versa.

**Comment by NickCraver** [comment]
Which versions of SQL are you running against here? That'll help narrow the cause.

**Comment by NickCraver** [comment]
Oh hmm, it looks like you're using the `master

**Comment by VictoriaD** [comment]
I've updated to overhaul, and the data seems to be in all of the instances now.
However, the Features section for each instance (on the `/about` page) seems to have gone completely. It just lists the name of each instance with the coloured dot icon for status. Is that correct?

**Comment by NickCraver** [comment]
@VictoriaD it's there, but as a tooltip now since that screen was getting a bit crowded with many servers. I can look at adding it back if the instance count is low or some such if you find it very helpful though, let me know!
