### ISSUE TITLE
ISQLVersionedObject with a min version above an instance's version is not ignored for that instance.

### ISSUE THREAD

**Issue by VictoriaD** [opserver/Opserver#133]
We have servers in a whole rainbow of versions, going back to 2000. I can see that the MinVersion of the class VolumeInfo is SQL2008R2.SP1. However, my older instances are marked as critcal on Volume. Well, querying Volume will fail because the query uses sys.dm_os_volume_stats which was not available until SQL2008R2.SP1. Hence that is the min version for volume!

Incidentally, the min volume of DatabaseFiles is listed as SQL2005.RTM, but the query for that also includes sys.dm_os_volume_stats. So it should probably be SQL2008R2.SP1.

I've been trying to find a place in the code to insert a check for the MinVersion before querying an ISQLVersionedObject, but the bit which fills the VersionSingletons dictionary is a static, so can't get the instance version number! Is there somewhere better to do this?

**Comment by NickCraver** [comment]
Hmm, that's bad - I'll take a look tonight. The current behavior you're seeing is definitely not intentional here.

**Comment by NickCraver** [comment]
Can you give latest `overhaul` a try? I pushed several fixes for earlier SQL versions tonight which should improve things quite a bit. If you can let me know what's still broken with old versions it'd be much appreciated!

**Comment by VictoriaD** [comment]
I've got the latest overhaul, and my older versions are no longer marked as critical! Thank you!

**Comment by NickCraver** [comment]
@VictoriaD in some bits I'm working on for permissions - it's just not going to make sense to continue supporting SQL 2000, or at least prevent it from breaking in some cases (let's say: if you have sysadmin permissions it'll *probably* work). How impactful is this?

**Comment by VictoriaD** [comment]
We're currently working on getting rid of our very last SQL2000 box, so happily it won't make any difference to us now.
