### ISSUE TITLE
Internal Server Error 500: sql/db/mydb/tables

### ISSUE THREAD

**Issue by win32nipuh** [opserver/Opserver#135]
I have connected 4 my SQL servers using sa user.
On any of databases when I click on database to I receive the error 500

```
Error loading
Status: Internal Server Error
Code: 500
Url: sql/db/mydb/tables

```

**Comment by NickCraver** [comment]
If you go to `/admin/errors`, do you see a more detailed error you can post here?

**Comment by win32nipuh** [comment]
Ah, yes, I see.
That is part of information:

> Object reference not set to an instance of an object.
> System.NullReferenceException
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at ASP._Page_Views_SQL_Databases_Modal_Tables_cshtml.Execute() in C:\inetpub\wwwroot\opserver\Views\SQL\Databases.Modal.Tables.cshtml:line 7
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
>    at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
>    at System.Web.WebPages.StartPage.ExecutePageHierarchy()
>    at System.Web.WebPages.StartPage.ExecutePageHierarchy()
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
>    at StackExchange.Profiling.Mvc.WrappedView.Render(ViewContext viewContext, TextWriter writer)
>    at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
>    at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by win32nipuh** [comment]
And my Roles:

User 	domain-test\administrator
Roles 	Authenticated, Exceptions, ExceptionsAdmin, HAProxy, HAProxyAdmin, SQL, SQLAdmin, Elastic, ElasticAdmin, Redis, RedisAdmin, Dashboard, DashboardAdmin, CloudFlare, CloudFlareAdmin, PagerDuty, PagerDutyAdmin, GlobalAdmin

**Comment by NickCraver** [comment]
Hmm, that would point to your instance being null/not found - was this just after a restart perhaps?

**Comment by win32nipuh** [comment]
It is strange because I have 4 SQL Server registered in opserver: 3 on one physical host and 1 on other. I have the same problem for all databases on all instances. 
I will restart server now and check again.... just 3 minutes

**Comment by NickCraver** [comment]
What is the name of the node? It's possible we have an encoding error somewhere and it's not getting passed.

Just to sanity check, are you using the `overhaul` branch, or `master`? `overhaul` is current code.

**Comment by win32nipuh** [comment]
I have downloaded from here
https://github.com/opserver/Opserver/archive/overhaul.zip

By the way all my SQL Server instances have names like hostname\sql2008R2, hostname\sql2012 etc

**Comment by NickCraver** [comment]
@win32nipuh Thanks, that was critical info - I just reproed and fixed in https://github.com/opserver/Opserver/commit/af72cc5d7f34403332a687128cbca0e9a240be47, can you please give latest a try?

**Comment by win32nipuh** [comment]
I have restarted physical server where are IIS with opserver and SQL Server 2012 instance installed. The same problem reproduced.

Also, the same error is in other places: 
```
Error loading
Status: Not Found
Code: 404
Url: sql/instance/summary/memory
Error loading

Status: Not Found
Code: 404
Url: sql/instance/summary/db-files
```
etc

probably  the reason is the same...

**Comment by win32nipuh** [comment]
Ok, I will get the latest version and try it.

**Comment by win32nipuh** [comment]
Yes, now it works! :-)
Thanx

**Comment by NickCraver** [comment]
Awesome, closing this out - thanks for the report!

**Comment by nickluu2018** [comment]
> I have downloaded from here
> https://github.com/opserver/Opserver/archive/overhaul.zip
> 
> By the way all my SQL Server instances have names like hostname\sql2008R2, hostname\sql2012 etc

Is it the latest version? I just download opserver-master.zip. Please advice

**Comment by nickluu2018** [comment]
> What is the name of the node? It's possible we have an encoding error somewhere and it's not getting passed.
> 
> Just to sanity check, are you using the `overhaul` branch, or `master`? `overhaul` is current code.

Hi Nick, what code should I use? "master" or "overhaul"
Thanks
