### ISSUE TITLE
No scrollbar for tables, views forms

### ISSUE THREAD

**Issue by win32nipuh** [opserver/Opserver#137]
When I click on database name for a SQL Server instance the form with Tables, Views, Backups etc displayed and right-side scrollbar is available, all is ok.

But if I click in this form 'Views' , 'Backups', 'Tables' menu - no scrollbar and it is impossible to see the rest of objects.
If I refresh the page - scrollbar again is here.
Tested in FF and Chrome.

**Comment by NickCraver** [comment]
Hmm yeah, Bootstrap/Bootbox bug...I'll see what I can do to fix that tonight.

**Comment by NickCraver** [comment]
@win32nipuh thanks for the report - fixed!
