### ISSUE TITLE
Errors(view) page incorrect layuot

### ISSUE THREAD

**Issue by win32nipuh** [opserver/Opserver#138]
I go to page 
http://serverhost/opserver/sql/instance?node=test-host\SQL2012

Then click on Errors(view) 
I see the page 'Errors last 6 hours' containing log records but long records are out of page, no wrapping records to fit them to page.

**Comment by NickCraver** [comment]
Fixed in the above commit - the no-wrap was unintentional in the port there. Thanks for the report!
