### ISSUE TITLE
Notification icon

### ISSUE THREAD

**Issue by wudzik** [opserver/Opserver#141]
There is a notification icon right next to the opserver logo. I guess it's showing number of errors/warnings/infos, but it is unclear where to search for this errors. Is there any plan to enhance it to show (maybe in some tooltip) actual problems for e.g. "SQL server (MSSQL-03) failed to connect" ?

**Comment by Tony-Mc** [comment]
As far as I know notifications in `overhaul` are being refactored. #119

**Comment by NickCraver** [comment]
Issues button is back in 6da147a06fe159c23621359a360e815ce43e07e5:
<img width="1114" alt="screen shot 2017-03-12 at 16 22 40" src="https://cloud.githubusercontent.com/assets/454813/23835633/1388c69e-0741-11e7-8000-8e4acfd7eba9.png">

I'll improve this further, but gave them a fair bit of love in the above.
