### ISSUE TITLE
SQL Query Detail doesn't handle EXECUTE PROC statements

### ISSUE THREAD

**Issue by afscrome** [opserver/Opserver#144]
The query detail view (`/sql/top/detail`) has some problems for query plans containing execute statements such as

```sql
CREATE TABLE #replies ( Id int NOT NULL PRIMARY KEY );
Insert Into #replies
exec sp_executesql N'select 1'
```

Specifically the plan XML contains the following statement, which leads to a null reference error in `ShowPlanXml.StatementTextWithoutInitialParams` due to there being no StatementText attribute.

```
<StmtSimple StatementId="2" StatementCompId="53" StatementType="EXECUTE PROC" RetrievedFromCache="true" />
```

Full Query Plan XML at https://gist.github.com/afscrome/49d48dc9d5a028befdbd

**Comment by NickCraver** [comment]
Good catch - latest should have a fix. I think the presentation here can be improved quite a bit, just need to focus some time on it.
