### ISSUE TITLE
Error: 'Sequence contains no elements'

### ISSUE THREAD

**Issue by win32nipuh** [opserver/Opserver#145]
http://localhost/opserver/sql/connections?node=sqlhost\SQL2008R2

> Sequence contains no elements
> System.InvalidOperationException
> 
> System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
>    at ASP._Page_Views_SQL_Operations_Top_Detail_cshtml.Execute() in C:\inetpub\wwwroot\opserver\Views\SQL\Operations.Top.Detail.cshtml:line 162
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
>    at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
>    at System.Web.WebPages.StartPage.ExecutePageHierarchy()
>    at System.Web.WebPages.StartPage.ExecutePageHierarchy()
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
>    at StackExchange.Profiling.Mvc.WrappedView.Render(ViewContext viewContext, TextWriter writer)
>    at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
>    at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
>

**Comment by NickCraver** [comment]
There's a fix in #146, but it needs a bit of love before merging. I'll merge it in as soon as it's simplified!

**Comment by NickCraver** [comment]
Fixed via #146 :)
