### ISSUE TITLE
Network Interfaces Don't Show Any Data

### ISSUE THREAD

**Issue by djlaney3** [opserver/Opserver#158]
When clicking the View link under network on the Stats box display area, the modal windows occasionally shows nothing other than Server name Interfaces title.  The rest of the modal window is empty.  On other occasions, a list of network adapters shows up, but with no relevant data - everything is blank or default values.  I'm not sure if this should be working yet or not.

**Comment by NickCraver** [comment]
Which provider are you using for the dashboard?

**Comment by djlaney3** [comment]
I'm using AD authentication using the wmi and sql providers.

Dennis J. Laney




On Sat, Apr 2, 2016 at 4:18 PM -0700, "Nick Craver" <notifications@github.com> wrote:





Which provider are you using for the dashboard?

---

**Comment by NickCraver** [comment]
Ah okay I suspected WMI - I'm not sure network is in there yet, I'll be taking a look (and spending a bit more time on Opserver) this weekend/week.

**Comment by djlaney3** [comment]
Thanks.  This project is great.   I'll keep putting in issues as I find them.

Dennis J. Laney




On Sat, Apr 2, 2016 at 4:23 PM -0700, "Nick Craver" <notifications@github.com> wrote:





Ah okay I suspected WMI - I'm not sure network is in there yet, I'll be taking a look (and spending a bit more time on Opserver) this weekend/week.

---

**Comment by NickCraver** [comment]
@djlaney3 I made a few enhancements here tonight (IPs and such), can you take another peek and see what's coming up? We need to dig a little if you're still not seeing interfaces.

**Comment by djlaney3** [comment]
I will test it out in the morning.

Dennis J. Laney




On Sat, Apr 2, 2016 at 7:10 PM -0700, "Nick Craver" <notifications@github.com> wrote:





@djlaney3 I made a few enhancements here tonight (IPs and such), can you take another peek and see what's coming up? We need to dig a little if you're still not seeing interfaces.

---

**Comment by djlaney3** [comment]
Just pulled down the latest and compiled/deployed.  Interfaces still not showing up for all servers. About half of them it shows.  I am looking for common traits between the non working ones, but I haven't found any yet.   What information do you need from me?

Date: Sat, 2 Apr 2016 19:10:50 -0700

**Comment by djlaney3** [comment]
Digging more into this.  When I run it from my Dev machine, all network data shows for all servers monitored.  However, when I deploy to my monitoring server (with the same configs), about half of the servers are missing network data.  Let me know what info you need from me.

**Comment by djlaney3** [comment]
@NickCraver I tracked this down somewhat.  It appears on Windows 2008 (any version), there is some extra permissions necessary for WMI network queries (outside of normal dcom & wmi security settings).  I tried multiple scenarios with the necessary user account, but the only fool proof way was to add the account to the local admin group on the windows 2008 servers.  Then it all works.  This explains why it worked from my Dev box, since I have perms on those servers.  I can do further testing if you need me to.

**Comment by NickCraver** [comment]
@djlaney3 I need to document permissions (and many things) quite a bit after finishing off /hub so I can merge into master. The digging there is very much appreciated, thank you! We could dig into which WMI grants are needed, but I wonder what the audience is there and if they'd deploy such grants via GPO or otherwise.

**Comment by djlaney3** [comment]
No problem on the digging.  I tried to isolate it, but wasn't able to pin down one setting or permission.  I was starting to feel like Server 2008 has an undocumented perm that is needed.  If you know of a setting or permission you want me to test, I certainly will.

Date: Mon, 4 Apr 2016 17:12:06 -0700

**Comment by NickCraver** [comment]
Closing this out to consolidate into #191 which is tracking the permissions needed.
