### ISSUE TITLE
Content/themes/light/styles style error 

### ISSUE THREAD

**Issue by chsword** [opserver/Opserver#160]
branch : overhual
Content/themes/light/styles.min.css

the style ".fade"

```
opacity: 0;
```

Will result a modal window cannot be displayed

**Comment by chsword** [comment]
in file \Content\bootstrap\less\component-animations.less
```
.fade {
  //opacity: 0;
  .transition(opacity .15s linear);
  &.in {
    opacity: 1;
  }
}
```
But I'm not sure if this is the right way.

**Comment by NickCraver** [comment]
What issue are you seeing? The intent here is for a modal to start with a class of `fade` and then `fade in` which uses CSS transitions for the fade (instead of say: JavaScript). I haven't heard any reports of this being broken - it's basic bootstrap bits. Can you provide more specifics on what issue you're actually having with the modals? Please include which browser you're using!

**Comment by chsword** [comment]
In Chrome.

When I call a dialog like 
click the link :
"SQL/ node / Job [view]" (/sql/instance?node=nodename#/sql/summary/jobs)
 "Dashboard / node / [view hardware]"(/dashboard/node?node=nodename#/dashboard/summary/hardware)

And the dialog is hidden(opacity: 0)

**Comment by kshyju** [comment]
Is this a specific browser you are getting this issue? It works fine for me in chrome.

**Comment by NickCraver** [comment]
This works fine for me as well - is it possible you have some Chrome extension breaking JavaScript to where the `in` class isn't getting added? Can you please check your console for errors?

**Comment by chsword** [comment]
Well, I guess this is my problem of publishing. I tried Debug locally under a minute, it was good.
Thanks

**Comment by chsword** [comment]
Solve  the problem.
Because I was upgrading from earlier versions.
So the directory: Content\js\plugins has the autocomplete.js.but the new version is removed.

But when the package is the package the plugin folder.
So autocomplete.js will be loaded. It affects the display of the Dialog

Removing this file just fine.

**Comment by NickCraver** [comment]
@chsword ahhh, thanks for following up on this - it may help someone else hitting the same later!
