### ISSUE TITLE
TSDBQuery: Problem converting dates in different cultures

### ISSUE THREAD

**Issue by evaristovidal** [opserver/Opserver#164]
I am using the overhaul branch and the bosun provider in the dashboard. Everything is working fine but the graphics for CPU and memory usage are not working. When accessing directly the graph url(for example http://localhost:81/dashboard/graph/MyServer/cpu) I am getting the following error:

 Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

Stack Trace:
   [KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key) +13937263
   StackExchange.Opserver.Data.Dashboard.Providers.<GetRecentAsync>d__21.MoveNext() +180
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13847892
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
  ........

After debugging a bit I have found that the issue was in TSDBQuery.GetMetric() when we create a new TSDBQuery:

```cs
public TSDBQuery(DateTime? startTime, DateTime? endTime = null)
{
	start = ConvertTime(startTime, DateTime.UtcNow.AddYears(-1));
	if (endTime.HasValue) end = ConvertTime(endTime, DateTime.UtcNow);
	queries = new List<object>();
}

public static string ConvertTime(DateTime? date, DateTime valueIfNull)
{
	return (date ?? valueIfNull).ToString("yyyy/MM/dd-HH:mm:ss");
}
```

The issue is that my system is configured in French and the date format that I am using is different, 07-04-16. To fix it and be able to show the graphics I had to replace the ConverTime method with the following line

```cs
return (date ?? valueIfNull).ToString("yyyy/MM/dd-HH:mm:ss", CultureInfo.InvariantCulture);
```

I am not sure if this fix is enough or might be better to use  ISO-8601 date format.

**Comment by NickCraver** [comment]
Indeed that is the correct fix (since TSDB has an expected format) - thanks!

**Comment by NickCraver** [comment]
@evaristovidal fix pushed for everyone else, thank you!
