### ISSUE TITLE
1 restoring database causes error for whole databases tab (every database on server)

### ISSUE THREAD

**Issue by VictoriaD** [opserver/Opserver#170]
Start a long database restore on a server.
Navigate to that server in Opserver.
Click on the databases tab.

You either get a timeout error, or a 'Database 'dbname' cannot be opened. It is in the middle of a restore.' error. Either way, you can't see any database information until it has finished.

**Comment by kshyju** [comment]
Do you absolutely  want to see db information while it is restoring ? This seems to me like, trying to run a car while the engine is being fixed. :)

**Comment by VictoriaD** [comment]
You can't see information for the other databases on the server. So one is restoring (don't need to see info), and the other 12 databases you can't see (these are not restoring, so you would like to see the information).

**Comment by kshyju** [comment]
I see. But i remember seeing other db information while one db state was in "Restoring".
