### ISSUE TITLE
No details with ElasticSearch 2.3.1

### ISSUE THREAD

**Issue by pascalcmd** [opserver/Opserver#178]
Hi,

I am trying to set Opserver with ElasticSearch 2.3.1 and it cannot get information about the cluster/nodes. I tried with ES 1.7 and it worked OOTB.

Am I missing something or is Opserver not compatible with ES 2.X?

Thanks.

**Comment by NickCraver** [comment]
It's compatible with 2.2, but possibly something new broken in 2.3 - any errors visible in `/admin/errors`? Also: using `overhaul` branch or `master`? (overhaul has the 2.x bits)

**Comment by pascalcmd** [comment]
I don't get any error from /admin/errors and I am using the master branch.

**Comment by pascalcmd** [comment]
Well actually, I did a git clone again and now it's working. I had an old version and did a git pull and it didn't update well I guess. So ... now it's working and thank you for your prompt answer.
