### ISSUE TITLE
Timezone settings - Inconsistent time displays

### ISSUE THREAD

**Issue by webash** [opserver/Opserver#180]
A default build and publish of the OpServer package doesn't seem to have timezone settings, nor use consistent time displays. For example:

![image](https://cloud.githubusercontent.com/assets/6205899/14718727/47848ace-07f0-11e6-9783-ae95db13e083.png)

- Graph shows 05:26
- Mouse over shows UTC of 17:26
- But local time (for the server running OpServer, and the local browser viewing it) is actually 18:26 BST/GMT+1

**Comment by NickCraver** [comment]
Thanks for the report - can you pull latest overhaul and give it a try? It was supposed to be UTC all around but the time scale for built-in UTC on d3 uses `%I` instead of `%H`, resulting in a 12 vs. 24-hour format on the 05 vs. 17.

**Comment by NickCraver** [comment]
Closing this out as it should be correct now - if it's not ping here for a reopen!

**Comment by Mike3131** [comment]
![1](https://cloud.githubusercontent.com/assets/19927178/16038985/15137d86-325a-11e6-9434-5865a297c1c7.png)
![2](https://cloud.githubusercontent.com/assets/19927178/16038986/1513f540-325a-11e6-8e65-fa3a3b310f9c.png)
hello @NickCraver 
•Graph shows 10:00
•Mouse over shows UTC of 10:00
•But local time (for the server running OpServer, and the local browser viewing it) is actually 18:00 
I want to know if the configration wrong.
