### ISSUE TITLE
Inactive tab - no data when coming back to tab

### ISSUE THREAD

**Issue by djlaney3** [opserver/Opserver#194]
When opserver is open in a tab that is not active (but previously was, with polled data displayed), when you come back to it after a while (1:22), it quickly flips to the red "no data successfully fetched for xxxx" for a few seconds before the regular polled data shows up.  Can this be remedied?

**Comment by NickCraver** [comment]
I over-corrected here by not polling *at all* when not viewing the tab, but that's not awesome for several reasons including application pool recycle lifetimes. I'll change this to be 10x slower when out of focus and update this issue when pushed.

**Comment by NickCraver** [comment]
Fixed in the commit above, grab latest - and thanks for the nudge here!
