### ISSUE TITLE
SQL Volumes sometimes duplicated on instance dashboard.

### ISSUE THREAD

**Issue by VictoriaD** [opserver/Opserver#198]
Select a SQL server instance and look at the Volumes section of the instance dashboard. Sometimes drives appear here multiple times.

This appears to be a result of the function sys.dm_os_volume_stats giving different results for different files. It is only the available bytes column that appears to change - so it's probably that the drive is busy at exactly the time the query is being run. Aggregating available bytes will solve this issue, so I have used min on my version.

**Comment by NickCraver** [comment]
Fix via #199, thanks!
