### ISSUE TITLE
Bug fixes and enhancements (primarily WMI provider)

### ISSUE THREAD

**Issue by batzen** [opserver/Opserver#200]
Hi and thanks for your great work first.

I would like to propose a few bug fixes and enhancements, but would like to ask for your opinion about them.

Bug fixes
- Network (WMI)
  - Detect correct interface name. Currently, during interface detection, Name from Win32_NetworkAdapter is used as the interface name. This does not work correctly when you got multiple adapters with the same name. Name from Win32_PerfFormattedData_Tcpip_NetworkInterface returns the Name from Win32_PnPEntity, thus resulting in some interfaces not being matched during utilization polling.
  - Interface caption should always be NetConnectionID and not Name if NetConnectionID == "Ethernet"

Enhancements
- CPU (WMI)
  - Gather correct CPU % for Hyper-V hosts. If we detect that we query a Hyper-V host we should use Win32_PerfFormattedData_HvStats_HyperVHypervisorLogicalProcessor instead of Win32_PerfFormattedData_PerfOS_Processor.
- Interface (PrimaryInterfaces)
  - IsLikelyPrimary: In my opinion this method should be changed to always return true if pattern is null , instead of matching against hard coded "team", "bond" etc..

I would happily contribute those changes to the overhaul branch.
@NickCraver Whats do you think about it?

**Comment by NickCraver** [comment]
I need to look at the primary interface bits (I can this weekend), but the rest sounds good. I've thought about these and haven't had the time - I'd welcome a pull request with those changes. The `IsLikelyPrimary` is a bit tricker...it's not so awesome across providers and maybe I need to change where that lives. I'd *love* to get the members of a interface team correctly out of WMI like I can with Bosun...but I've yet to find a reliable source of this data. Any insight there would also be much appreciated.

**Comment by batzen** [comment]
If you don't mind i would fix/enhance a few more things regarding WMI.
- Network utilization for virtual adapters (including teams, virtual hyper-v, virtualbox etc..)
- I can try to find out how to get team members
- Getting virtual machine nodes through WMI

Regarding primary interface:
I still got problems with the meaning of "primary interface". What is a primary interface? I would suggest renaming it to "dashboard interface" as that is what it's used for, isn't it?
That way we could rename IsLikelyPrimary to something like IsDashboardInterface and change the method to return all physical interfaces if no dashboardInterfacePattern is set.
Maybe interfaces should get a flag "IsPhysical" to make it clear what kind of interface it is.
The reason for needing IsPhysical is that, as soon as i make team utilization visible through WMI, the utilization is somewhat counted twice because every single physical interface reports it and the team reports the aggregated values from multiple physical interfaces. The same should be true for virtual Hyper-V and even VirtualBox adapters.

And to clarify some meanings in WMI:
- Interface = physical
- Adapter = physical + virtual
Win32_PerfFormattedData_Tcpip_NetworkInterface only returns utilization for physical adapters. Win32_PerfFormattedData_Tcpip_NetworkAdapter returns utilization for physical + virtual adapters.

How are virtual adapters for Hyper-V handled in bosun?

So my suggested changes:
- Change "primary" to "dashboard"
- Add "IsPhysical" to interface
- Dashboard shows, if no pattern is set, only physical interface utilization

**Comment by batzen** [comment]
Closing this as you merged my PR. Thanks. ;-)
