### ISSUE TITLE
Use Win32_PerfRawData instead of Win32_PerfFormattedData in WMI provider

### ISSUE THREAD

**Issue by batzen** [opserver/Opserver#202]
The WMI provider is currently using Win32_PerfFormattedData to gather utilization data.
This has a few disadvantages:
- Queries are slow. Getting CPU for example takes ~250ms using FormattedData and ~10ms using RawData.
- Some information is lost because FormattedData only reports uint/int and not float in some cases. One example for this is AvgDisksecPerRead (response time) when getting volume performance. AvgDisksecPerRead on FormattedData only reports full seconds thus reporting "0" in most cases when response time is, in reality, below one second (for example 600ms or 20ms).

I would include these changes in my fork and add those to my WMI PR.
@NickCraver Do you agree on these changes?

**Comment by batzen** [comment]
Switching to PerfRawData would also have the advantage of providing more data or more precise data.
Currently the minimum polling interval is set to 10 seconds which means that we only get a 1 second snapshot of utilization every 10 seconds.
By switching to PerfRawData we get the average utilization during that period of time. Which is, in my opinion, much better.

**Comment by NickCraver** [comment]
Hey @batzen no complaints at all - I would only ask that you just submit several PRs here so that they're concise/readable. I can merge stuff like this in as soon as I can parse it and test locally. Smaller PRs rather than something monolithic is always preferred.

**Comment by batzen** [comment]
I also prefer smaller PRs. The problem i currently have with that is that almost all changes depend on each other... :-(

**Comment by NickCraver** [comment]
Hwy @batzen, any updates here? I'm still very curious about improvements on the WMi front. 

Related: I've pushed a lot of the major async overhauls needed for efficiency (and I'll continue to improve the first-hit experience).

**Comment by batzen** [comment]
I got everything working in my fork.

As said in #201 i still need to know which changes you would accept from my fork and which ones would get rejected.

You can review my changes at https://github.com/batzen/Opserver

If you decide to only accept parts of my changes i can still create a new branch/fork and only make the changes you would accept there.

And i would need to sync my fork ofc. ;-)

**Comment by batzen** [comment]
Closing this one as you merged my PR. Thanks. ;-)
