### ISSUE TITLE
Dose MySQL support?

### ISSUE THREAD

**Issue by ZhiqiangTao** [opserver/Opserver#214]

**Comment by JustinPealing** [comment]
No, there is no support for MySQL execution plans, only Microsoft SQL Server Execution Plans.

**Comment by NickCraver** [comment]
Not at the moment no, but there is progress on the .NET Core MySQL driver (the community version) which may offer hope. Th queries completely differ for the DMVs, though.

**Comment by NickCraver** [comment]
I'm closing this out as there is no action to take really. I think this will be an ideal candidate for plugins later - which is an achievable goal in a few months with the work the ASP.NET team is doing.
