### ISSUE TITLE
Elasticsearch 5.0 Compatibility

### ISSUE THREAD

**Issue by nlowe** [opserver/Opserver#221]
As far as I can tell, the only compatibility problems with ES 5.0 is dropping the `all` parameter from `_nodes/stats` and renaming `hostname` to `host`:

```diff
diff --git a/Opserver.Core/Data/Elastic/ElasticCluster.Nodes.cs b/Opserver.Core/Data/Elastic/ElasticCluster.Nodes.cs
index 40b62e7..0eeac57 100644
--- a/Opserver.Core/Data/Elastic/ElasticCluster.Nodes.cs
+++ b/Opserver.Core/Data/Elastic/ElasticCluster.Nodes.cs
@@ -16,7 +16,7 @@ public partial class ElasticCluster
                 var result = (await GetAsync<ClusterNodesInfo>("_nodes").ConfigureAwait(false))?.Prep();
                 if (result == null) return null;

-                var stats = await GetAsync<ClusterNodesStats>("_nodes/stats?all").ConfigureAwait(false);
+                var stats = await GetAsync<ClusterNodesStats>("_nodes/stats").ConfigureAwait(false);
                 if (stats == null) return result;

                 foreach (var s in stats.Nodes)
@@ -279,7 +279,7 @@ public class NodeStats
                 public string Name { get; internal set; }
                 [DataMember(Name = "transport_address")]
                 public string TransportAddress { get; internal set; }
-                [DataMember(Name = "hostname")]
+                [DataMember(Name = "host")]
                 public string Hostname { get; internal set; }
                 [DataMember(Name = "indices")]
                 public IndexStats Indexes { get; internal set; }
```

Without these changes, most of the node stats show up as unknown, and the status icon next to the cluster name reports 400 errors in the tooltip:

![image](https://cloud.githubusercontent.com/assets/794251/19873905/fd658e76-9f97-11e6-8efb-5e910b20f0c4.png)

**Comment by NickCraver** [comment]
Well, this sucks. I've berated them before about changing stuff like this that's a PITA across versions. Monitoring APIs shouldn't be needlessly broken like this.

I'll have to spin up 5.x to test some fixes here, since Opserver must continue to support all versions. Thanks for letting me know exactly what's broken, this is a huge time saver.

**Comment by NickCraver** [comment]
I have pushed a fix for one half on this, but I'm discussing with the Elastic folks the very unecessary breaking change on the `all` parameter (which wasn't documented either) over here: https://github.com/elastic/elasticsearch/issues/21410

**Comment by NickCraver** [comment]
@nlowe can you please give latest a try? Elasticsearch 5.0 should work now, but if you see any other breaks I'll open this back and address anything you find.

Thanks!

**Comment by nlowe** [comment]
@NickCraver so far, looks like this fixed it, thanks for the quick turnaround! I'll keep an eye out for any other breakage.
