### ISSUE TITLE
SQL Stats panel misaligned

### ISSUE THREAD

**Issue by afscrome** [opserver/Opserver#231]
Just upgraded to the latest, and I noticed the stats in the SQL Stats pane are misaligned.  (Memory should be under CPU, not to the right).

![image](https://cloud.githubusercontent.com/assets/289860/21848312/09803646-d7f8-11e6-984d-eccf94ed1c86.png)

**Comment by afscrome** [comment]
This is in Chrome 55.

**Comment by NickCraver** [comment]
Which OS are you on? I'm having trouble making this happen, happy to fix if I could repro.

**Comment by afscrome** [comment]
I'm on Windows 7, zoomed in at 100%.  The cells do align correctly at some zoom levels (see below).  The value-block divs with progress bars are coming out at 42.2px with the others at at 41.8px. 

* 80%: Works
* 90%: Broken
* 100%: Broken
* 110%: Works
* 125%: Broken
* 150%: Works

**Comment by NickCraver** [comment]
I never was able to reproduce this - are you still seeing it?

**Comment by NickCraver** [comment]
Closing out with no info to go on - unable to get this to repro and was likely a browser layout issue temporarily.
