### ISSUE TITLE
does it suppurt rabbitmq?

### ISSUE THREAD

**Issue by 564064202** [opserver/Opserver#234]
does it suppurt rabbitmq?

**Comment by georgeduckett** [comment]
Not at present but it could be supported in the future. It's always good to have different options, although I'd like to get other bugs/issues ironed out before adding other providers. You're welcome to submit a pull request.

**Comment by NickCraver** [comment]
In what capacity do you mean? The answer is "no" regardless - Opserver does nothing with RabbitMQ, but I'm curious what you're after. Monitoring RabbitMQ, or Opserver supporting it in some way for messaging?

**Comment by phillijw** [comment]
You could probably monitor queue size pretty easily

**Comment by NickCraver** [comment]
Closing this out barring more info - not sure what to answer here beyond the above.
