### ISSUE TITLE
Clarification on Redis Config

### ISSUE THREAD

**Issue by nlowe** [opserver/Opserver#242]
So in trying to get opserver to connect to our redis instances that are password protected (see comment in #195) I discovered that we also had to specify the password in the `instances` subsection for `allServers`. An exception is thrown on trying to connect otherwise.

What's the difference between `allServers` and `Servers` config sections?

**Comment by NickCraver** [comment]
I've updated the example config to hopefully be much clearer - can you please take a look? The current version is here: [RedisSettings.example.json](https://github.com/opserver/Opserver/blob/efac956a3ed898b79e698e63bf0b5e5cb1dc6635/Opserver/Config/RedisSettings.example.json)

**Comment by nlowe** [comment]
Yeah, that makes more sense (github butchers the comments in the preview sadly). Thanks!
