### ISSUE TITLE
Where the monitor data saved?

### ISSUE THREAD

**Issue by yunfeifei** [opserver/Opserver#245]
How to config opserver to save monitor data and where it saved to,i find it after restartup,the data have lost!

**Comment by smurariu2** [comment]
It lives in memory until the app pool is recycled

**Comment by NickCraver** [comment]
@smurariu2 is correct if using WMI the data store is in-memory only, so there's no database dependency.

If you are using Bosun or Orion, the data is pulled from their stores.
