### ISSUE TITLE
Redis:  cannot connect

### ISSUE THREAD

**Issue by Oleg26Dev** [opserver/Opserver#255]
● d-srv: 6379 (View INFO)

Data unavailable for Core

Unable to fetch from Redis: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING @    at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log)
   at StackExchange.Opserver.Data.Redis.RedisInstance.GetConnection(Boolean allowAdmin, Int32 syncTimeout) in D:\_Work\Opserver-overhaul\Opserver.Core\Data\Redis\RedisInstance.cs:line 136
   at StackExchange.Opserver.Data.Redis.RedisInstance.get_Connection() in D:\_Work\Opserver-overhaul\Opserver.Core\Data\Redis\RedisInstance.cs:line 48
   at StackExchange.Opserver.Data.Redis.RedisInstance.<<get_Config>b__23_0>d.MoveNext() in D:\_Work\Opserver-overhaul\Opserver.Core\Data\Redis\RedisInstance.Config.cs:line 17

**Comment by Oleg26Dev** [comment]
There is at Dashboard:
"● 2 Missing/Unknown Instances "

That is my config
{
    "allServers": {
        "name": "All",
        "instances": [
            {
                "name": "Core",
				"port": "6379",
				"analysisRegexes": {
					 "**Dev**": "^d-",
					 "**Live**": "^srv-",
					}
          }
        ]
    },
"Servers":[
      {
         "name":"d-11",
         "instances":[
            {
               "name":"d-11",
               "port":"6379"
            }
         ]
      },
      {
         "name":"d-srv",
         "instances":[
            {
               "name":"d-srv",
               "port":"6379"
            }
         ]
      }
   ]	

}



What is incorrect?

**Comment by Oleg26Dev** [comment]
I have replaced the server name with "localhost", it works.  It seems it cannot recognize the hostname for the local host.

**Comment by NickCraver** [comment]
If you try to connect with `redis-cli` and the hostname, does it work? I'm not sure if this is a DNS resolution issue (which would be my first guess).

**Comment by AlexSikilinda** [comment]
@Oleg26Dev this may happen because SSL is disabled by default.

Try changing `public bool UseSSL { get; set; } = false;` to `public bool UseSSL { get; set; } = true;` in `RedisSettings.cs`.

It probably may be configured from the config file, but I didn't try that. @NickCraver may help with this.

**Comment by NickCraver** [comment]
Closing out to cleanup, looks like a local DNS failure and not an Opserver issue directly.
