### ISSUE TITLE
"Clear visible errors" from search redirects to wrong place

### ISSUE THREAD

**Issue by AdamMaras** [opserver/Opserver#257]
**Steps to reproduce:**

1. Select a specific app in the Exceptions view
2. Search for exceptions from that app using the top search bar
3. Click "Clear visible errors"

**Expected behavior:**

After clearing the errors, Opserver redirects to the Exceptions view filtered to the app that was previously selected.

**Actual behavior:**

After clearing the errors, Opserver redirects to `/exceptions` and all apps' exceptions are shown.

**Comment by NickCraver** [comment]
Fix is in cbe47afe347b6015d065f11296a9486f9bf014d2 (as well as a few related cases) - thanks!
