### ISSUE TITLE
SQL server Named Instances and IIS Monitoring

### ISSUE THREAD

**Issue by omukwenyi** [opserver/Opserver#262]
I can configure monitoring of the default SQL instances but I am unable to get any headway with named instances  (MACHINE\INSTANCE). How do I represent them in the config file?

Is there any way to monitor IIS or any other service using Opserver?

**Comment by omukwenyi** [comment]
After stepping through the code, I discovered that named instances have to be configured as MACHINE\\INSTANCE. The double backslash was the trick.

**Comment by NickCraver** [comment]
You're right, this sucked. I'm overhauling the config files with a lot of comments as the first step of documentation for Opserver now. I've renamed them as well so they get proper syntax highlighting: https://github.com/opserver/Opserver/blob/master/Opserver/Config/SQLSettings.example.json
