### ISSUE TITLE
Server Status due to Ping

### ISSUE THREAD

**Issue by JoshKeegan** [opserver/Opserver#268]
Hi,
We're just starting to use OpServer in production; so first of all, thanks it's looking great!

One small thing we've noticed though is that all of the servers we're monitoring (so far) apart from the one running bosun show with a warning:
![image](https://user-images.githubusercontent.com/1682204/27585783-7c3154f2-5b35-11e7-9322-5ce9865d9c0f.png)

Looking in the code it seems to be in `BosunDataProvider.GetNodeStatus` they're being marked as unreachable by:
```cs
if (host.ICMPData?.Values.All(p => p.TimedOut) == true)
    return NodeStatus.Unreachable;
```

This makes sense as we don't operate internal DNS and so server hostnames won't be resolved to IPs & Bosun won't be able to ping the servers.
Is there a setting to disable no ping producing a warning?  

For now, I expect we'll just comment those lines.
Cheers,
Josh

**Comment by NickCraver** [comment]
I've pushed a new option in latest to ignore the ping status, like this:
```json
  "providers": {
    "bosun": {
      "host": "...",
      "apiKey": "...",
      "ignorePing": true
    }
```

Please let me know if you have any issues!
