### ISSUE TITLE
Feature Request: Percentage Information in Redis Memory Analysis

### ISSUE THREAD

**Issue by kylebrandt** [opserver/Opserver#272]
It would be helpful to have a relative numbers when looking at a memory analysis in the Key Pattern section:

![screen shot 2017-08-17 at 9 29 29 am](https://user-images.githubusercontent.com/1692624/29414732-b8646204-832e-11e7-96a1-d2c67ea05765.png)

That way one can quickly see that one of the patterns is using X% of memory. I think this would be fine in a tooltip if the problem is UI clutter. In particular with the total being a different unit that the line numbers (bytes vs GB).

**Comment by NickCraver** [comment]
Added in 942802f27e367244960b4d54c2c20673cfe8b930 above, example view:
![image](https://user-images.githubusercontent.com/454813/32706144-07d18c1e-c7e9-11e7-935a-675e787cad05.png)
