### ISSUE TITLE
Loading more exceptions doesn't respect current exceptions group 

### ISSUE THREAD

**Issue by AlexSikilinda** [opserver/Opserver#273]
Scenario: I select an exception group, let's say "DEV". I scroll to the bottom of the page thus triggering `exceptions/load-more`  API. The problem is that this API call returns exceptions from all groups, not only "DEV".

This happens because we do not pass `group` parameter from JS:
![image](https://user-images.githubusercontent.com/1301414/29523852-f6a58672-8696-11e7-8add-b852041a2f78.png)

The solution is to add `group: options.group` to javascript object. 
Can submit a pull request but wonder if it was done intentionally.

**Comment by NickCraver** [comment]
Nope just missed it - if you submit a PR I'd love to have your name in the commit list :) Thanks!
