### ISSUE TITLE
Error when Opening .sln

### ISSUE THREAD

**Issue by mqbk** [opserver/Opserver#278]
I did a fork from the master branch. When I attempt to open the .sln, I get the error that Opserver (load faield) and Opserver.Core (load failed). When I attempt to reload both Opserver and Opserver.Code I get the following messages:
F:\Work\Opserver\Opserver\Opserver.csproj : error  : The attribute "Version" in element <PackageReference> is unrecognized.  F:\Work\Opserver\Opserver\Opserver.csproj

F:\Work\Opserver\Opserver.Core\Opserver.Core.csproj : error  : The attribute "Version" in element <PackageReference> is unrecognized.  F:\Work\Opserver\Opserver.Core\Opserver.Core.csproj

Any suggestions?

**Comment by NickCraver** [comment]
What version of Visual Studio are you using? 2017 15.3 and higher is needed to open and build the solution.

**Comment by mqbk** [comment]
I am guessing that is the problem. I am running VS 2015 version 14.0

**Comment by mqbk** [comment]
would I be able to use the community version?

**Comment by NickCraver** [comment]
@mqbk yep!

**Comment by mqbk** [comment]
Thank you. I got it working now.
