### ISSUE TITLE
Install/Run

### ISSUE THREAD

**Issue by anatolieStepanov** [opserver/Opserver#279]
Can I ran this app on a IIS localhost . I dont know how to deploy it for testing. I am using VS 2017, building solution, and pointing IIS to folder with source code.(dont know what to do with 2 class libraries).

**Comment by anatolieStepanov** [comment]
Or can I debug this code somehow? thank you

**Comment by kshyju** [comment]
You can publish the Opeserver project and point your IIS site to that location. It should work fine.

**Comment by anatolieStepanov** [comment]
Yes I started with that but I get "can't reach this page". Thank you for your response, just wanted to make sure I am not missing something.
