### ISSUE TITLE
Web publish error

### ISSUE THREAD

**Issue by OverwindSlash** [opserver/Opserver#286]
Hi, Guys
When I tried to publish Opserver project to Web Deploy Package，I  got this error on Web Publish Activity window :
D:\Workspace\Github\Opserver\Opserver.csproj(0,0): Error MSB4057: The target "Package" does not exist in the project.

I wonder to known whether it's a configuration error of my IDE (VS 2017 15.3.5) or something else?  Thanks in advance.

BTW. This project can run properly when debugging.

**Comment by OverwindSlash** [comment]
Hi, I think I probably found the problem.
Change
<Import Project="..\lib\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
To
<Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" />
in Opserver.csproj  Line 679
and the build process can be done properly.

**Comment by NickCraver** [comment]
Fixed in latest for all, thanks!
