### ISSUE TITLE
The target "MSDeployPublish" does  not exist in the project

### ISSUE THREAD

**Issue by AlexSikilinda** [opserver/Opserver#290]
Hi,

I pulled the last version and tried to deploy it via VS "publish" menu (we use publish profile file which points to Azure). It used to work, but now I get "The target "MSDeployPublish" does not exist in the project" error.

A little investigation showed that it was caused by commit `939c7331441fdf8ad85ed9fe6c2e8658fafc3acc` "Defunct the VS install on build servers" in which `Opserver.csproj` was modified so that 

    <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />

was replaced with

    <Import Project="..\lib\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />

Reverting this change fixed my issue.

**Comment by AlexSikilinda** [comment]
Possibly a duplicate fo #286

**Comment by NickCraver** [comment]
Can you please try latest?

**Comment by NickCraver** [comment]
This should be resolved in latest, closing out :)
