### ISSUE TITLE
Support for Windows Services - request for feedback

### ISSUE THREAD

**Issue by KennethScott** [opserver/Opserver#292]
I recently added support for inquiring on the current state of Windows Services ([Win32_Services](https://msdn.microsoft.com/en-us/library/aa394418(v=vs.85).aspx)) via the WMI provider and I was wondering what kind of interest there might be in it.  

I basically added a new Windows Services partial view underneath the Interfaces.  You control which services are monitored via a new DashboardSettings property that can be specified at the global, category, or perNodeSettings levels.  The property itself is literally the [WQL](https://msdn.microsoft.com/en-us/library/aa394606(v=vs.85).aspx) WHERE clause you want to use to select the services (i.e. 'Name = 'W3SVC').  

This is what it looks like:
![Screenshot](https://user-images.githubusercontent.com/823499/32750727-30b9892e-c889-11e7-9858-41a375041d0d.png)

Next I'll try to add buttons in the view to allow you to Stop/Start the individual services.

And I'm also considering adding something to the dashboard to show the number of running/stopped services for the node.

Ultimately I'd love to add support for alerts, but let's not get carried away.  :)

Is this something you'd consider merging in?  Are others interested in this?

**Comment by djlaney3** [comment]
I'd like to see that for sure.

**Comment by omukwenyi** [comment]
Yeah. Most definitely.

**Comment by NickCraver** [comment]
Closing this out to cleanup - it'll land shortly in #293, thanks for the feedback and the contribution!
