### ISSUE TITLE
Windows Server2008 R2 WMI Unable to read

### ISSUE THREAD

**Issue by l2999019** [opserver/Opserver#295]
I can't read 52 of the information.like the graph
![image](https://user-images.githubusercontent.com/10385855/33192609-ba5c4b9e-d0fe-11e7-9f5e-b2296a7e65b6.png)

 but I can read it in the windows performance monitor   like the graph
![image](https://user-images.githubusercontent.com/10385855/33192655-0799c49a-d0ff-11e7-92d6-6dda336bca05.png)

**Comment by NickCraver** [comment]
I see you're on a different culture as well - to be honest I'm not sure here. We haven't had any 2008 servers to test with in quite some time (and people are upgrading these days), so unless someone can point me in the right direction here with a test, I don't have enough info to go on. It could be:
- Permissions
- Culture differences causing a query miss
- The APIs are totally different and/or missing
- Something else?
