### ISSUE TITLE
Filtering in SQL TOP page leads to 404

### ISSUE THREAD

**Issue by elvishfiend** [opserver/Opserver#299]
We've got OpsServer installed as an application on a site, so the url is something like `https://ops.site.com/OpsServer/`

When applying a filter on the page `ops.site.com/OpsServer/sql/top?node=[node]`, it's instead setting the address as `ops.site.com/sql/top?node=[node]&[filter criteria]`, (dropping the OpsServer path) leading to a 404

**Comment by NickCraver** [comment]
Fixed! Thanks for the report :)
