### ISSUE TITLE
Recommended method for managing configs

### ISSUE THREAD

**Issue by stijnherreman** [opserver/Opserver#300]
What is the recommended way for managing your own configs, after having cloned this repo? Should you create a branch with your own configs, and then regularly merge from upstream?

How do you do it internally at SO?

**Comment by NickCraver** [comment]
At SO what we do is maintain another repo with configs and merge that in on a build, simply copying the folder into \Config. But, the .config files are intentionally ignored from git, so you can just leave them in the directory as you pull latest.

In ASP.NET Core, I'll switch to their configuration system which will allow *many* more options already built by others, namely:
- Many more stores (json, xml, database, redis, etc.)
- Secrets support (for services that need passwords)
- A lot less code, as it's in the framework now

**Comment by stijnherreman** [comment]
That sounds like a good method, thanks.
