### ISSUE TITLE
Database names with spaces are not return error 404 when clicked on

### ISSUE THREAD

**Issue by SQLSourcerer** [opserver/Opserver#301]
In the Databases tab, when I click on a database name that has spaces in it, instead of showing me the database details, I get an error 404

**Comment by SQLSourcerer** [comment]
I think I may have found a solution

- In web.config, on the system.webServer/security/requestFiltering tag, add the allowDoubleEscaping attribute with value true
- In the Databases view, on the tr tag, change the data-dbname attribute to add .UrlEncode()
- In the DatabaseDetail action of SQLController, UrlDecode the database name as it's being assigned to the model property

**Comment by SQLSourcerer** [comment]
I found one more place that needs UrlEncode added: In the Databases.Modal view, the RenderLink function

**Comment by NickCraver** [comment]
Fixed in 48c55ff59afc1adefd16617e01464a33cdc40757, thanks!
