### ISSUE TITLE
Decimal Params not being generated properly in SQL Plan Detail view

### ISSUE THREAD

**Issue by elvishfiend** [opserver/Opserver#313]
In the SQL Plan Detail view, the list of Compiled Params seems to bug out if there's a decimal param.
The decimal param is missing its scale, and missing the trailing comma.
There's also an additional list of params that don't show on other plan details.

This means that you can't just copy the query from OpsServer into SSMS like you can with other plan details.

![image](https://user-images.githubusercontent.com/1051830/36647632-cf02d5a4-1adc-11e8-8fdc-809e867de75a.png)

**Comment by NickCraver** [comment]
I pushed a fix up for this, thanks for the heads up and let me know if there are any other problems with it!

**Comment by elvishfiend** [comment]
@NickCraver Seems to be working fine, thanks.

**Comment by elvishfiend** [comment]
@NickCraver looks like it's still got the issue where it's including the param types just before the SELECT
I.e. `(@p0 char(1),@p1 decimal(35,6),@p2 decimal(35,6),@p3 char(1))` in the original pic
