### ISSUE TITLE
Build server error (AppVeyor)

### ISSUE THREAD

**Issue by itssimple** [opserver/Opserver#327]
Hi!

We're trying to automate upgrades of Opserver while still retaining our configs.

So I made a batch-script that clones the master-branch.
It's supposed to do a nuget restore / dotnet restore and then build it and deploy to a temporary directory.

But I get a strange error about Dapper that I cannot quite figure out what I've done wrong with.

Here's the log from the script:
https://paste.fuelrats.com/ohotazadol.txt

And here's the actual script that I'm using:
https://paste.fuelrats.com/bokayeneku.bat

When I run the script from my own command line, everything works. msbuild runs fine, and deploy works. But when I'm running this in our AppVeyor instance (where our dev-computers are part of the cloud), I get this error.

**Comment by NickCraver** [comment]
Some SDK behavior here has changed - can you try running a `dotnet restore` in the root before building? or a `msbuild /t:Restore`?
