### ISSUE TITLE
If connectionstrings have a backslash in them, app crashes

### ISSUE THREAD

**Issue by waynebrantley** [opserver/Opserver#34]
If connectionstrings have a backslash in them, like server\instance, it crashes.  Using server\\instance works.

**Comment by NickCraver** [comment]
@chriswedgwood this is now fixed and tested in the new overhaul code, see https://github.com/opserver/Opserver/commit/514bfcf011e38156fe439bbe3970ba2ffaf70906

Thanks for the report!
