### ISSUE TITLE
Build Errors 

### ISSUE THREAD

**Issue by FLSQLGeek** [opserver/Opserver#354]
**When running the build process below:**

C:\inetpub\wwwroot\Opserver-master>"C:\Windows\Microsoft.NET\Framework64\v4.0.30
319\MSBuild.exe" "Opserver.sln" /p:configuration=debug

**I then get the following errors:**

Microsoft (R) Build Engine version 4.7.3062.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
Build started 9/5/2019 1:37:36 PM.
Project "C:\inetpub\wwwroot\Opserver-master\Opserver.sln" on node 1 (default ta
rgets).
ValidateSolutionConfiguration:
  Building solution configuration "debug|Any CPU".
Project "C:\inetpub\wwwroot\Opserver-master\Opserver.sln" (1) is building "C:\i
netpub\wwwroot\Opserver-master\Opserver.Core\Opserver.Core.csproj" (2) on node
1 (default targets).
_C:\inetpub\wwwroot\Opserver-master\Opserver.Core\Opserver.Core.csproj(1,1): err
or MSB4041: The default XML namespace of the project must be the MSBuild XML na
mespace. If the project is authored in the MSBuild 2003 format, please add xmln
s="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> elemen
t. If the project has been authored in the old 1.0 or 1.2 format, please conver
t it to MSBuild 2003 format.
Done Building Project "C:\inetpub\wwwroot\Opserver-master\Opserver.Core\Opserve
r.Core.csproj" (default targets) -- FAILED._

Project "C:\inetpub\wwwroot\Opserver-master\Opserver.sln" (1) is building "C:\i
netpub\wwwroot\Opserver-master\Opserver\Opserver.csproj" (3) on node 1 (default
 targets).
C:\inetpub\wwwroot\Opserver-master\Opserver\Opserver.csproj(45,54): error MSB40
66: The attribute "Version" in element <PackageReference> is unrecognized.
Done Building Project "C:\inetpub\wwwroot\Opserver-master\Opserver\Opserver.csp
roj" (default targets) -- FAILED.

Done Building Project "C:\inetpub\wwwroot\Opserver-master\Opserver.sln" (defaul
t targets) -- FAILED.

Build FAILED.

"C:\inetpub\wwwroot\Opserver-master\Opserver.sln" (default target) (1) ->
"C:\inetpub\wwwroot\Opserver-master\Opserver.Core\Opserver.Core.csproj" (defaul
t target) (2) ->
  C:\inetpub\wwwroot\Opserver-master\Opserver.Core\Opserver.Core.csproj(1,1): e
rror MSB4041: The default XML namespace of the project must be the MSBuild XML
namespace. If the project is authored in the MSBuild 2003 format, please add xm
lns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> elem
ent. If the project has been authored in the old 1.0 or 1.2 format, please conv
ert it to MSBuild 2003 format.

"C:\inetpub\wwwroot\Opserver-master\Opserver.sln" (default target) (1) ->
"C:\inetpub\wwwroot\Opserver-master\Opserver\Opserver.csproj" (default target)
(3) ->
  C:\inetpub\wwwroot\Opserver-master\Opserver\Opserver.csproj(45,54): error MSB
4066: The attribute "Version" in element <PackageReference> is unrecognized.

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.06

C:\inetpub\wwwroot\Opserver-master>pause
Press any key to continue . . .

Sincerely,

Jason

**Comment by NickCraver** [comment]
This will go away with the .NET Core version (almost ready to merge) - we'll be on .NET Core 3.1 and then a simple `dotnet build` will do everything we need. In this case it looks like you're using an older version of MSBuild...but .NET Core will eliminate that. Plus we can ship it as a container and such.
