### ISSUE TITLE
PagerDuty APIv1 Retired

### ISSUE THREAD

**Issue by tshirey** [opserver/Opserver#360]
Now that PagerDuty has retired API v1, has anyone created a  new example file to use?

**Comment by NickCraver** [comment]
The latest example file removes the URL (since it's always the same) - you can find it in `master` here: [Opserver/Config/PagerDutySettings.example.json](https://github.com/opserver/Opserver/blob/408597868e9af6f1b0179d7c54fec9cd02b56ef5/Opserver/Config/PagerDutySettings.example.json)
