### ISSUE TITLE
BosunDataProvider: ApiResponse can be null here

### ISSUE THREAD

**Issue by rhubley** [opserver/Opserver#380]
https://github.com/opserver/Opserver/blob/ed57f51d26a061e75359c1a3245786b795ae93b7/Opserver.Core/Data/Dashboard/Providers/BosunDataProvider.cs#L180

JoinNetwork can handle a Null value is below could work or shortcut a return
``` 
return JoinNetwork(apiResponse?.Series) ?? new List<DoubleGraphPoint>();

**Comment by NickCraver** [comment]
Fixed in #380, thanks!
