### ISSUE TITLE
Opserver Documentation - Broken Link/Missing File

### ISSUE THREAD

**Issue by abjoseph** [opserver/Opserver#384]
In the Opserver Configuration Section, the hyperlink "**Here’s an example configuration monitoring lots of things with comments**" is broken and the file it refers to is not in the repository, I also searched the `craver/aspnetcore` branch. A screenshot of the issue is shown below:

![image](https://user-images.githubusercontent.com/26844547/96289364-ebd2fb00-0fb2-11eb-866d-b6a6b9f572b0.png)

![image](https://user-images.githubusercontent.com/26844547/96289422-0c02ba00-0fb3-11eb-9873-e2402a3834b1.png)

**Comment by Sacha-K** [comment]
This was fixed in commit 68fc395e10e6285e18640c82a8ab92e77e4062e5

**Comment by NickCraver** [comment]
Closing out to tidy up!
