### ISSUE TITLE
Update nugets build errors on Opserver ASP

### ISSUE THREAD

**Issue by fasteddys** [opserver/Opserver#400]
Hello I am getting errors on latest NuGet updates, with asp CORE 6, can you please update and check in.

![image](https://user-images.githubusercontent.com/96149622/147900323-41668ec8-38e3-4513-8ec6-0c47d0dff4b0.png)

**Comment by NickCraver** [comment]
@fasteddys Which branch are you updating here? I'd imagine there are maybe some build errors on net6.0 for the craver/aspnetcore - I'm not primary on this at the moment but will take a poke tonight.

**Comment by fasteddys** [comment]
Hi @NickCraver you are correct it is the AspNetCore, it was very few, like only 6 or 7 errors. 

I was able to fix 4 of those easily by swapping out the deprecated namespaces / function calls.

**Comment by NickCraver** [comment]
@fasteddys I'm taking a look but will need someone to give it a spin and see if everything still works. Doing a lot of other net6.0 love at the same time.

**Comment by NickCraver** [comment]
@fasteddys I opened a PR here but can't test at the moment, if you're able to give it a go... https://github.com/opserver/Opserver/pull/401

**Comment by fasteddys** [comment]
Thanks I am trying it now, the build was smooth, polite reminder, some of the Nugets are showing out of date.

Is there some guidance on how to contribute with some Modules/new functionality or how to extend this, perhaps a `picture / hooks / components / architecture`

![image](https://user-images.githubusercontent.com/96149622/148154728-d0785245-5d45-4657-9846-2955398fabf9.png)
