### ISSUE TITLE
Additional filtering in exceptions view

### ISSUE THREAD

**Issue by peschkaj** [opserver/Opserver#404]
The Exceptions tab provides a lot of information to help investigate exceptions. One problem that we've noticed is there's no way to search for a particular exception _and_ filter by host, URL, etc.

When prototyping this, we've added separate boxes for filtering:
![image](https://user-images.githubusercontent.com/71570/152587437-c30a8b69-fc62-4564-98b7-b001def1f0f8.png)

I'm interested in your thoughts about adding some kind of additional filtering like this to Opserver to help rapid drilldown to problem areas.

Ideally, a user would be able to search on any of the columns that appear in the Exceptions view

**Comment by dalehhirt** [comment]
Would it be easier to just have one text box, then filter on all columns by that text box?

**Comment by peschkaj** [comment]
That's what the current search box does. There are cases where the same string appears in multiple fields, making the search noisy. 

After discussing this with @NickCraver, we're going to use the same filter UI that's on pages like Top SQL.
