### ISSUE TITLE
AG Cluster Info not displaying on SQL Dashboard

### ISSUE THREAD

**Issue by cdhunt** [opserver/Opserver#423]
The entire AG panel isn't rendering on an instance of Opserver. We have the configuration defined in envvars like this.

```
Modules__Sql__clusters__0__description = Azure Channels Cluster
Modules__Sql__clusters__0__name = Az Channels
Modules__Sql__clusters__0__nodes__0__name = chsql001.ds.stackexchange.com
Modules__Sql__clusters__0__nodes__1__name = chsql002.ds.stackexchange.com
Modules__Sql__defaultConnectionString = Server=$ServerName$,1433;Persist Security Info=False;User ID=user;Password="password";MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
```

It looks like Opserver is pulling AG info.
![image](https://github.com/opserver/Opserver/assets/114173/579190b5-feea-4d64-b890-77b063c05227)

**Comment by NickCraver** [comment]
oo interesting - what are you seeing where the AG view should be?

**Comment by NickCraver** [comment]
In that case, it sounds like it doesn't have any clusters or AGs beneath - has this worked against Azure before? I'm not sure if the information available on-prem/local is actually exposed in all the Azure DMVs, of if anyone has tried yet...so not sure what our baseline is. Any idea if this has worked?

**Comment by NickCraver** [comment]
Gotcha - @tarynpratt do you have any idea what is or isn't exposed in the DMVs on the Azure side here? It's possible that it's not exposed or we need to tweak queries here to consume it from the Azure side if available. 

Queries we're running today are:
- [SQLNode.AvailabilityGroups.AGDatabaseReplica.cs](https://github.com/opserver/Opserver/blob/main/src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGDatabaseReplica.cs)
- [SQLNode.AvailabilityGroups.AGInfo.cs](https://github.com/opserver/Opserver/blob/main/src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGInfo.cs)
- [SQLNode.AvailabilityGroups.AGListener.cs](https://github.com/opserver/Opserver/blob/main/src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGListener.cs)
- [SQLNode.AvailabilityGroups.AGListenerIPAddress.cs](https://github.com/opserver/Opserver/blob/main/src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGListenerIPAddress.cs)
- [SQLNode.AvailabilityGroups.AGReplica.cs](https://github.com/opserver/Opserver/blob/main/src/Opserver.Core/Data/SQL/SQLNode.AvailabilityGroups.AGReplica.cs)

I don't have a setup to connect this to...but if we had an environment, could take a peek at what it's doing.

**Comment by cdhunt** [comment]
There should be nothing Azure-specific other than network access.

This is from one of the secondary VMs.

<img width="938" alt="image" src="https://github.com/opserver/Opserver/assets/114173/fde1cf05-fe19-4e25-864a-abd93fd7a51e">
<img width="964" alt="image" src="https://github.com/opserver/Opserver/assets/114173/a423d5a2-a849-4606-a392-06bc6a7d7a93">

**Comment by NickCraver** [comment]
I'm not sure I agree with "there should be nothing Azure-specific" - the normal case we had was _inside a Windows cluster_, which is what the view was assuming and aggregating data on to represent child AGs. Isn't this a very different scenario spanning outside a Windows cluster and not Distributed AGs which also had to be figured out along the way. I'm all for making this work, but as I understand it, this isn't the same topology under the covers. That almost certainly needs some love, but I'm a bit blindly guessing at what that _should_ look like...it needs hands-on love to figure out queries and see what we should be connecting where. Happy to help soon as time allows, but I'd need a repro to query as a starting point.

If y'all are working on this with the repro/code, happy to do a call helping (will be free some this afternoon).

**Comment by NickCraver** [comment]
@cdhunt ACK - if it still isn't working after connectivity issue please let me know, happy to help get you going here. If it just works that'd be a pleasant surprise - often we had to make a few tweaks for the additional scenarios, so don't hesitate to poke as you get further!

**Comment by cdhunt** [comment]
Confirmed. It works once connectivity to the Primary works.

**Comment by NickCraver** [comment]
Oo awesome! Glad it's the easy path :)

**Comment by tarynpratt** [comment]
Easiest issue I've ever been tagged on. :)
