### ISSUE TITLE
Need .json file to monitor AD Server & DNS Server

### ISSUE THREAD

**Issue by Hsingh79** [opserver/Opserver#83]
Hello,

I Installed & Configured OPServer for my SQL Server through "SQLSettings.json.example" file and It is working perfect. I am not from programming filed so I need help.
I need .json files like "SQLSettings.json.example". I want to add and Monitor my AD (windows active directory) server & DNS Server as well as other servers (File Server, Print Server, Web Serevr or a Normal Server) in my network.

Please Advise me ASAP !

Thanks & Regards,
Hariom Prakash Singh. Delhi, India

**Comment by NickCraver** [comment]
Hi @Hsingh79,
This wasn't possible before without Orion, but I have now merged in the WMI provider and am starting on the Bosun provider (we're doing a lot of Bosun-side work as well). If you only need to monitor Windows systems, grab the latest code and you can now stick in a specific host list to monitor via the WMI provider. Just uncomment that section out and swap it for Orion.

The examples are in [DashboardSettings.json.example](https://github.com/opserver/Opserver/blob/master/Opserver/Config/DashboardSettings.json.example), here's what it would look like:

```json
{  
  "providers": {
    "wmi": {
      "nodes": [ "host1", "host2", "host3" ],
      "staticDataTimeoutSeconds": 300,
      "dynamicDataTimeoutSeconds": 5,
      "historyHours": 2
    }
  },
  //...other config...
}
```

I'll be working on much better documentation now that I have some time to spend on this in the coming weeks. Please let me know if this works for your case!
