### ISSUE TITLE
can redis be set with same port different servers?

### ISSUE THREAD

**Issue by soulrenger** [opserver/Opserver#85]
Can this redis monitor be set with same port but different ip address and server name?I tried a lot of config but always get errors when reading the other redis status,Could you give a example of the right way to config it ?Thanks a lot.

**Comment by NickCraver** [comment]
Yes, absolutely. The `Servers` section can specify instances per-server. I've updated the example config in the commit above. 

For reference, here's an example minimal `RedisSettings.json`:

    {
      "Servers": [
        { "name": "ny-redis01" },
        { "name": "ny-redis02" },
        {
          "name": "ny-mlredis01",
          "instances": [ { "name": "Machine Learning", "port": "6379" } ]
        }
      ]
    }
