### ISSUE TITLE
Performance stats don't gather when using instance names

### ISSUE THREAD

**Issue by justinvaldez** [opserver/Opserver#86]
I've been working with this for a couple months and it seems that regardless of what attempts I make to reconfigure the Instance name or other options, I cannot get the performance stats to show up on servers that have named instances. If it uses the default instance I get all the data I would expect to get.

Wondering if this has to do with some of the instance issues other people have had. Also wondering if anyone has a workaround that would help me with this. 

Thanks In advance for any ideas. 

![image](https://cloud.githubusercontent.com/assets/9000732/8253976/ccb1761c-1651-11e5-9c7d-a571f349a47c.png)

![image](https://cloud.githubusercontent.com/assets/9000732/8253985/e7adcb14-1651-11e5-9ec3-a311691da9cd.png)

**Comment by kwilson1030** [comment]
In the SQLInstance,cs file add

            if (name.Contains('\\'))
            {
                ObjectName = objectName.IsNullOrEmptyReturn(objectName, "MSSQL$" + name.Split('\\')[1]);
            }
            else
            { 
                ObjectName = objectName.IsNullOrEmptyReturn(objectName, "SQLServer");
            }
to the SQLInstance function. Around line 40.
This is probably not the best way but it works.

**Comment by TheRockStarDBA** [comment]
I have the same problem. I tried what @kwilson1030 suggested, but it is breaking.

**Comment by NickCraver** [comment]
Fixed in https://github.com/opserver/Opserver/commit/514bfcf011e38156fe439bbe3970ba2ffaf70906, in the overhaul branch, sorry this took quite a while to get around to.
