### ISSUE TITLE
The Compiler throw an error and  exit 'csc2.exe stop work' when building opserver project.

### ISSUE THREAD

**Issue by mushroomsir** [opserver/Opserver#89]
Environment  vs2013 update 2.
Error	1	"csc2.exe" exited with code -532462766.	Opserver.Core.

**Comment by validide** [comment]
Had a similar issue when starting this under IIS but it got solved after updating the NuGet packages

**Comment by mushroomsir** [comment]
Thank you for your answers, that's right.

**Comment by NickCraver** [comment]
@mushroomsir can you please confirm latest works please? Days are packed right now so Opserver hasn't gotten a lot of love recently but hoping time frees up in the next month or so.

**Comment by mushroomsir** [comment]
Yes it's working after update all NuGet packages.

**Comment by NickCraver** [comment]
Alrighty, thanks!
