### ISSUE TITLE
DATABASE INSTANCES BREAK LINKS

### ISSUE THREAD

**Issue by fallenidol** [opserver/Opserver#96]
If sql databases are specified in the settings with their instance names (i.e. MYSERVER\SQL2012) then this break some of the links....the databases jobs link for instance...404 error.

**Comment by NickCraver** [comment]
@fallenidol thanks for the report, this should be fixed in the current overhaul branch, see commit: https://github.com/opserver/Opserver/commit/514bfcf011e38156fe439bbe3970ba2ffaf70906
