### ISSUE TITLE
Divide By Zero Error

### ISSUE THREAD

**Issue by fallenidol** [opserver/Opserver#97]
SQLINstance.Database.cs

These 2 lines cause divide by zero errors sometimes...when NumReads and NumWrites is 0....

            public double AvgReadStallMs { get { return StallReadMs / NumReads; } }
            public double AvgWriteStallMs { get { return StallWriteMs / NumWrites; } }

**Comment by NickCraver** [comment]
This should be fixed if you grab latest - thanks!
